//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCFucktory.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articulo
    {
        public Articulo()
        {
            this.MovimientoDetalle = new HashSet<MovimientoDetalle>();
        }
    
        public string Articulo_id { get; set; }
        public string Descripcion { get; set; }
        public int StockMaximo { get; set; }
        public int StockMinimo { get; set; }
        public int StockCritico { get; set; }
        public int Categoria_ID { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual ICollection<MovimientoDetalle> MovimientoDetalle { get; set; }
    }
}
