//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCFucktory.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categoria
    {
        public Categoria()
        {
            this.Articulo = new HashSet<Articulo>();
        }
    
        public int Categoria_ID { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<Articulo> Articulo { get; set; }
    }
}
