//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCFucktory.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovimientoDetalle
    {
        public int Transaccion_ID { get; set; }
        public int Linea { get; set; }
        public string Articulo_ID { get; set; }
        public int BodegaSalida_ID { get; set; }
        public int BodegaEntrada_ID { get; set; }
        public int Cantidad { get; set; }
    
        public virtual Articulo Articulo { get; set; }
        public virtual Bodega Bodega { get; set; }
        public virtual Bodega Bodega1 { get; set; }
        public virtual Movimiento Movimiento { get; set; }
    }
}
