//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCFucktory.DALC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FuckingDBEntities : DbContext
    {
        public FuckingDBEntities()
            : base("name=FuckingDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Articulo> Articulo { get; set; }
        public DbSet<Bodega> Bodega { get; set; }
        public DbSet<Categoria> Categoria { get; set; }
        public DbSet<Comuna> Comuna { get; set; }
        public DbSet<Movimiento> Movimiento { get; set; }
        public DbSet<MovimientoDetalle> MovimientoDetalle { get; set; }
        public DbSet<Region> Region { get; set; }
        public DbSet<Ubicacion> Ubicacion { get; set; }
    }
}
