//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCFucktory.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ubicacion
    {
        public Ubicacion()
        {
            this.Bodega = new HashSet<Bodega>();
        }
    
        public int Ubicacion_ID { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string TorreBlock { get; set; }
        public Nullable<int> NroDpto { get; set; }
        public int Numero { get; set; }
        public int Comuna_ID { get; set; }
    
        public virtual ICollection<Bodega> Bodega { get; set; }
        public virtual Comuna Comuna { get; set; }
    }
}
